### ISSUE TITLE
Hello, how to set the data set path or the data set structure

### ISSUE THREAD

**Issue by af-doom** [CengizhanYurdakul/YOLOv8-Openvino#1]

**Comment by CengizhanYurdakul** [comment]
Hello,
It is enough to have images in the dataset path you will give. It only supports `.jpg`, `.png` and `.jpeg` extensions.

    .
    ├── src 
    │    ├── datasets
    │           ├ image_1.jpg
    │           ├ image_2.png
    │           ├ image_3.jpeg
    .             .
    .             .
