### ISSUE TITLE
NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\\Users\\HYP\\AppData\\Local\\Temp\\tmpzvqeckrc\\model.bin'

### ISSUE THREAD

**Issue by Ylogical** [CengizhanYurdakul/YOLOv8-Openvino#7]
请问这个应该如何解决呀！

**Comment by CengizhanYurdakul** [comment]
I am using Ubuntu and I see that the error you get gives a path in Windows. There may be a problem with this. If you are using a terminal when giving paths, can you try again by changing the default parameters in `main.py` instead? You can also try moving the model into the repository.
